spring.application.name=quickbite

# MongoDB Configuration
spring.mongodb.uri=mongodb://127.0.0.1:27017
spring.mongodb.database=quickbite

# AWS S3 Configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketname=tanu-quickbite

server.port=8088


jwt.secret.key = qwertyuiopasdfghjklzxcvbnm1234567890etrcvhbjyhn


razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}
